version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:  
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hci
      GO_ENV: dev
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: hci
    ports:
      - "3306:3306"
